#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use GitDeployer\Commands\LoginCommand;
use GitDeployer\Commands\LogoutCommand;
use GitDeployer\Commands\StatusCommand;
use GitDeployer\Commands\ConfigCommand;
use GitDeployer\Commands\AddCommand;
use GitDeployer\Commands\RemoveCommand;
use GitDeployer\Commands\InfoCommand;
use GitDeployer\Commands\HistoryCommand;
use GitDeployer\Commands\InitCommand;

use Symfony\Component\Console\Application;

// -> Initialize the Symfony\Console component and our commands
$deployer = new Application('Git-Deployer', '@package_version@');
$deployer->add(new LoginCommand());
$deployer->add(new LogoutCommand());
$deployer->add(new ConfigCommand());
$deployer->add(new StatusCommand());
$deployer->add(new AddCommand());
$deployer->add(new RemoveCommand());
$deployer->add(new InfoCommand());
$deployer->add(new HistoryCommand());
$deployer->add(new InitCommand());
$deployer->run();