#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use GitDeployer\Commands\VersionCommand;
use Symfony\Component\Console\Application;

$deployer = new Application('Git-Deployer', '@package_version@');
$deployer->run();